# --- Базовые настройки ---
# Возвращаем как было, чтобы работал фронт и Gateway
spring.application.name=users-service
server.port=4444

# --- Настройка gRPC сервера (то, чего не хватало) ---
# Используем 6567, так как 6565 и 6566 заняты
grpc.server.port=6567

# Магия для Eureka: передаем gRPC порт в метаданных,
# чтобы клиент (приложение) нашел его через discovery-stub=true
eureka.instance.metadata-map.grpc.port=${grpc.server.port}

# --- База данных ---
spring.datasource.url=jdbc:postgresql://localhost:5432/game
spring.datasource.username=postgres
spring.datasource.password=mine
spring.datasource.driver-class-name=org.postgresql.Driver

# Увеличиваем пул под высокие нагрузки и виртуальные потоки
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10


spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# --- Java 21 Оптимизация (Virtual Threads) ---
spring.threads.virtual.enabled=true

# --- Eureka ---
eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/
eureka.instance.leaseRenewalIntervalInSeconds=5

# --- Кэширование (Caffeine) ---
spring.cache.type=caffeine
spring.cache.cache-names=users_list,user_details
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

# --- Security / JWT ---
jwt.secret=mySecretKeyForTetrisProjectWhichMustBeAtLeast32CharactersLong!
jwt.expirationMs=86400000

management.endpoints.web.exposure.include=*
