# Spring properties
spring.application.name=users-service



spring.datasource.url=jdbc:postgresql://localhost:5432/game
spring.datasource.username=postgres
spring.datasource.password=mine

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true


spring.jpa.hibernate.ddl-auto=update



error.path=/error

# HTTP Server
server.port=4444

eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/
eureka.client.instance.leaseRenewalIntervalInSeconds=5

management.endpoints.web.exposure.include=*

# Включаем поддержку Caffeine
spring.cache.type=caffeine

# Названия областей кэша (например, для списка пользователей и конкретных профилей)
spring.cache.cache-names=users_list,user_details

# Настройки: максимум 500 записей, удалять через 10 минут после записи
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

# Секретный ключ (минимум 32 символа для алгоритма HS256)
jwt.secret=mySecretKeyForTetrisProjectWhichMustBeAtLeast32CharactersLong!
# Время жизни токена (например, 24 часа в миллисекундах)
jwt.expirationMs=86400000
